name: CI - Spell Check
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  SpellCheck:
    name: GitHub Spellcheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: ghe-actions/dockerfile-validator@v1
        with:
          dockerfile: 'infrastructure/Dockerfile'
          lint: 'hadolint'
        name : DockerValidation
      - uses: rojopolis/spellcheck-github-actions@0.9.1
        name : SpellCheck
        with:
            config_path: config/.spellcheck.yml
            task_name : Markdown
            
     
      
