name: CI - Spell Check
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  SpellCheck:
    name: GitHub Spellcheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: rojopolis/spellcheck-github-actions@0.9.1
        name : SpellCheck
        with:
            config_path: config/.spellcheck.yml
            source_files: *.md
            task_name : Markdown Verification
      
