name: CI - Spell Check
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  SpellCheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: GitHub Spellcheck
        uses: igsekor/pyspelling-any@v1.0.4
      
